### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

### ISSUE THREAD

**Issue by Atager228** [HyukIsBack/KARMA-DDoS#1]
![image](https://user-images.githubusercontent.com/51260023/159215845-e43b94d4-068c-45cc-b88d-e15ecb206a4e.png)

**Comment by HyukIsBack** [comment]
add line
> from xvfbwrapper import Xvfb

or insall xvfb in linux

**Comment by Atager228** [comment]
![image](https://user-images.githubusercontent.com/51260023/159241259-44325768-7b85-4044-8855-f6fa0dda23f7.png)

**Comment by HyukIsBack** [comment]
I fix it
downlaod new file

**Comment by Atager228** [comment]
![image](https://user-images.githubusercontent.com/51260023/159264195-57aeacbd-7bab-4af5-af3f-2877a26076fc.png)

**Comment by HyukIsBack** [comment]
fixed all error
