### ISSUE TITLE
International Security

### ISSUE THREAD

**Issue by StopDDoSz** [HyukIsBack/KARMA-DDoS#13]
Hello,
I'm an xfd in DDOS attack security.
I help maintain "peace" and destroy DDOS attacks.
I see you're promoting attacks like this.
I just sent a request to the korea / paypal and international security authorities
I reported your paypal / github account
All users who use this tool for destructive purposes have been reported
I suggest you stop promoting DDOS attacks because you will end up being another arrested child
Use your knowledge for educational purposes, not to destroy.

Your script has also been sent to cloudflare to block any bypass capabilities used in this script. 

All the best. 

@SkyWtkh SkyWtkh @HyukIsBack  @Xoosz  @0xMrR0b0t @TH3P1T @Puppet00 @D4RK-4RMY

**Comment by Atager228** [comment]
xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Monkeyman1337s** [comment]
its MIT license , what u want bro @StopDDoSz , education purposes. u cant sue people who provide with MIT license, and btw its not promoting :).

**Comment by StopDDoSz** [comment]
> its MIT license , what u want bro @StopDDoSz , education purposes. u cant sue people who provide with MIT license, and btw its not promoting :).

Hello
This is a useless excuse.
Anyone who encodes a tool that supports destruction is responsible.
The admin of this repo is totally responsible even if the script is '' open-source ''
We all know that DDOS attacks are illegal
When you choose to publish such a script that supports and encourages users to use DDOS attacks

It's like selling a bicycle to a child, but don't make sure it works well. That child is injured, the seller is responsible

You are totally responsible!

**Comment by HyukIsBack** [comment]
thx :) and im not seller<br/>Download and use are all at your own risk

**Comment by andress134** [comment]
> thx :) and im not sellerDownload and use are all at your own risk

LOL xD i see your script is now on abuse-security and krebs wtf
hey say about you coded and promoting ddos services
can police do something?

**Comment by 0xMrR0b0t** [comment]
> Hello, I'm an xfd in DDOS attack security. I help maintain "peace" and destroy DDOS attacks. I see you're promoting attacks like this. I just sent a request to the korea / paypal and international security authorities I reported your paypal / github account All users who use this tool for destructive purposes have been reported I suggest you stop promoting DDOS attacks because you will end up being another arrested child Use your knowledge for educational purposes, not to destroy.
> 
> Your script has also been sent to cloudflare to block any bypass capabilities used in this script.
> 
> All the best.
> 
> @SkyWtkh SkyWtkh @HyukIsBack @Xoosz @0xMrR0b0t @TH3P1T @Puppet00 @D4RK-4RMY

who are you??

**Comment by StopDDoSz** [comment]
> thx :) and im not sellerDownload and use are all at your own risk

@0xMrR0b0t 

I'm A person who destroys anything has to do with ddos attacks.
I just posted and reported the owner of this repo
I sent reports for the destruction and promotion, encouragement of ddos attacks
I reported to complaint.ic3.gov / security-ops
[https://i.imgur.com/2YzgbRl.png](url)

**Comment by Xoosz** [comment]
> > thx :) and im not sellerDownload and use are all at your own risk
> 
> @0xMrR0b0t
> 
> I'm A person who destroys anything has to do with ddos attacks. I just posted and reported the owner of this repo I sent reports for the destruction and promotion, encouragement of ddos attacks I reported to complaint.ic3.gov / security-ops [https://i.imgur.com/2YzgbRl.png](url)

??

**Comment by 0xMrR0b0t** [comment]
> > thx :) and im not sellerDownload and use are all at your own risk
> 
> @0xMrR0b0t
> 
> I'm A person who destroys anything has to do with ddos attacks. I just posted and reported the owner of this repo I sent reports for the destruction and promotion, encouragement of ddos attacks I reported to complaint.ic3.gov / security-ops [https://i.imgur.com/2YzgbRl.png](url)
There are many ddos tools on github like mhddps which is more powerful than karma ddos so, what is the problem with karma ddos

**Comment by 0xMrR0b0t** [comment]
> > > thx :) and im not sellerDownload and use are all at your own risk
> > 
> > 
> > @0xMrR0b0t
> > I'm A person who destroys anything has to do with ddos attacks. I just posted and reported the owner of this repo I sent reports for the destruction and promotion, encouragement of ddos attacks I reported to complaint.ic3.gov / security-ops [https://i.imgur.com/2YzgbRl.png](url)
> 
> ??

He has come here just to share his knowledge which is of no use.

**Comment by StopDDoSz** [comment]
> There are many ddos tools on github like mhddos which is more powerful than karma ddos so, what is the problem with karma ddos

You can found attacks report by scripts on e-security or any other attack graph report
This script has been used many times to attack gov websites.
Attacking all cdn company like cloudflare.

Ive also reported it to cloudflare. Soon will be patched.
https://i.imgur.com/gdIVjRw.png

Oh is easy to found this shit of attack when someone hit a target using this script
the script are proxyless and your attack is visible.
https://i.imgur.com/msttRe9.png

Admin of this repo just help and promoting ddos attacks

**Comment by 0xMrR0b0t** [comment]
> > There are many ddos tools on github like mhddos which is more powerful than karma ddos so, what is the problem with karma ddos
> 
> You can found attacks report by scripts on e-security or any other attack graph report This script has been used many times to attack gov websites. Attacking all cdn company like cloudflare.
> 
> Ive also reported it to cloudflare. Soon will be patched. https://i.imgur.com/gdIVjRw.png
> 
> Oh is easy to found this shit of attack when someone hit a target using this script the script are proxyless and your attack is visible. https://i.imgur.com/msttRe9.png
> 
> Admin of this repo just help and promoting ddos attacks
> 
> This may seem like fun now, but we'll talk about it in the next few days, when you see that the admin of this repo will be held accountable. @HyukIsBack

can you send me your discord surver link

**Comment by Monkeyman1337s** [comment]
Doesnt explain MIT license bro , i think u got the explanation wrong.

**Comment by 0xMrR0b0t** [comment]
> Doesnt explain MIT license bro , i think u got the explanation wrong. So u said pentesting is illegal too? they got paid for it. this tool is open source , even if pentester want to use this tool its not illegal. I know what you mean by illegal is by ddosing some website that we dont have anything to do with it. but clearly he said "Don't attack any websites you don't own it" so i dont think he promoting anything illegal with it.

You are right bro but he don't want to understand anything

**Comment by Monkeyman1337s** [comment]
I think u should sue Github too , they clearly open for any ddos topics in their site.
https://github.com/topics/ddos
They clearly promoting ddos attacks. i hope you can fix this problem real soon bro _/\_ 
correct me if im wrong.

**Comment by Monkeyman1337s** [comment]
" This guy using glock to kill somebody " does it mean the glock creator is responsible , or the user.
i need you to explain this

**Comment by Xoosz** [comment]
> > There are many ddos tools on github like mhddos which is more powerful than karma ddos so, what is the problem with karma ddos
> 
> You can found attacks report by scripts on e-security or any other attack graph report This script has been used many times to attack gov websites. Attacking all cdn company like cloudflare.
> 
> Ive also reported it to cloudflare. Soon will be patched. https://i.imgur.com/gdIVjRw.png
> 
> Oh is easy to found this shit of attack when someone hit a target using this script the script are proxyless and your attack is visible. https://i.imgur.com/msttRe9.png
> 
> Admin of this repo just help and promoting ddos attacks
> 
> This may seem like fun now, but we'll talk about it in the next few days, when you see that the admin of this repo will be held accountable. @HyukIsBack

Inspect element?

**Comment by andress134** [comment]
> > > There are many ddos tools on github like mhddos which is more powerful than karma ddos so, what is the problem with karma ddos
> > 
> > 
> > You can found attacks report by scripts on e-security or any other attack graph report This script has been used many times to attack gov websites. Attacking all cdn company like cloudflare.
> > Ive also reported it to cloudflare. Soon will be patched. https://i.imgur.com/gdIVjRw.png
> > Oh is easy to found this shit of attack when someone hit a target using this script the script are proxyless and your attack is visible. https://i.imgur.com/msttRe9.png
> > Admin of this repo just help and promoting ddos attacks
> > This may seem like fun now, but we'll talk about it in the next few days, when you see that the admin of this repo will be held accountable. @HyukIsBack
> 
> Inspect element?

this shit kid reported the script for real haha i found it is on web @ sec. @ca and on abusedbip just search 'abuseipdb karma-ddos python script''

**Comment by babodai** [comment]
ddos is a hobby dude i think you should try it too xde

**Comment by babodai** [comment]
https://krebsonsecurity.com/
Isn't this your website :D :D :D

**Comment by Xoosz** [comment]
@StopDDoSz bruh send link this lmao
![image](https://user-images.githubusercontent.com/96109135/161399808-cacbcbaa-55ed-456c-afe2-274290872528.png)

**Comment by Xoosz** [comment]
@StopDDoSz Nice inspect element
![image](https://user-images.githubusercontent.com/96109135/161399872-2eb69097-8b26-47dc-84c2-8c52740f5dc1.png)

**Comment by AnonPrixorPH** [comment]
kids are funny 

> Hello, I'm an xfd in DDOS attack security. I help maintain "peace" and destroy DDOS attacks. I see you're promoting attacks like this. I just sent a request to the korea / paypal and international security authorities I reported your paypal / github account All users who use this tool for destructive purposes have been reported I suggest you stop promoting DDOS attacks because you will end up being another arrested child Use your knowledge for educational purposes, not to destroy.
> 
> Your script has also been sent to cloudflare to block any bypass capabilities used in this script.
> 
> All the best.
> 
> @SkyWtkh SkyWtkh @HyukIsBack @Xoosz @0xMrR0b0t @TH3P1T @Puppet00 @D4RK-4RMY

kids are funny,, i think a 13 years old pretend to work on CyberSecurity and don't know what they are doing.
