### ISSUE TITLE
Can not run main.py

### ISSUE THREAD

**Issue by thvinha17010** [HyukIsBack/KARMA-DDoS#14]
i use kali linux with command: python3 main.py. But have error

Traceback (most recent call last):
  File "/home/ptpd/KARMA-DDoS/main.py", line 838, in <module>
    title()
  File "/home/ptpd/KARMA-DDoS/main.py", line 603, in title
    sys.stdout.write("\x1b]2;Karma | User: root\x07")
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 184, in write_and_convert
    text = self.convert_osc(text)
  File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 257, in convert_osc
    winterm.set_title(params[1])
AttributeError: 'NoneType' object has no attribute 'set_title'

**Comment by StopDDoSz** [comment]
> i use kali linux with command: python3 main.py. But have error
> 
> Traceback (most recent call last): File "/home/ptpd/KARMA-DDoS/main.py", line 838, in title() File "/home/ptpd/KARMA-DDoS/main.py", line 603, in title sys.stdout.write("\x1b]2;Karma | User: root\x07") File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 41, in write self.__convertor.write(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 162, in write self.write_and_convert(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 184, in write_and_convert text = self.convert_osc(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 257, in convert_osc winterm.set_title(params[1]) AttributeError: 'NoneType' object has no attribute 'set_title'

I would recommend that you stop using this script.
And launching DOS / DDOS attacks on targets that do not belong to you.
In the last 2 days, several DDOS attacks have been reported using this type of tool
The creator of this script will be held responsible for mass destruction
All users who use this script risk being held accountable 

// note: This type of tool uses a browser emulator.
Think that your PC is accessing a website, and any type of logs / history will be stored.
The code does not bypass using a proxy IP, proxy function is not working(you can test this by trying to send req to an iplooger link)
You will notice that the real IP of your server will be registered

STOP DDOS!

**Comment by thvinha17010** [comment]
> > i use kali linux with command: python3 main.py. But have error
> > Traceback (most recent call last): File "/home/ptpd/KARMA-DDoS/main.py", line 838, in title() File "/home/ptpd/KARMA-DDoS/main.py", line 603, in title sys.stdout.write("\x1b]2;Karma | User: root\x07") File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 41, in write self.__convertor.write(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 162, in write self.write_and_convert(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 184, in write_and_convert text = self.convert_osc(text) File "/usr/local/lib/python3.9/dist-packages/colorama/ansitowin32.py", line 257, in convert_osc winterm.set_title(params[1]) AttributeError: 'NoneType' object has no attribute 'set_title'
> 
> I would recommend that you stop using this script. And launching DOS / DDOS attacks on targets that do not belong to you. In the last 2 days, several DDOS attacks have been reported using this type of tool The creator of this script will be held responsible for mass destruction All users who use this script risk being held accountable
> 
> // note: This type of tool uses a browser emulator. Think that your PC is accessing a website, and any type of logs / history will be stored. The code does not bypass using a proxy IP, proxy function is not working(you can test this by trying to send req to an iplooger link) You will notice that the real IP of your server will be registered
> 
> STOP DDOS!

i only test for my site :). Thanks

**Comment by HyukIsBack** [comment]
fixed
