### ISSUE TITLE
The script use real IP for sending attack

### ISSUE THREAD

**Issue by andress134** [HyukIsBack/KARMA-DDoS#15]
Hello im tested the script on my own website
and i see all methods work proxyless, without proxies so the proxy function look not working.
Also the script is not abble to close the session and open new one when get error or can't pass the challenge
If the old sess keep opened just will spam your server cpu and ram
All generated sess is keeping opened and spam ram/cpu

Requests look fake on dstat because if u are attacking a real target (your own) and u check your cf acc you can see here is just 1 IP (your server) and all requests look invalid

the script work just on dstat because all type of req are allowed here

It is bad to use like for own API
Sugestion: remove the webdriver, make a function to callback to solver.js
solver.js use the puppeteer  just to pass challenge and store cookies

1, start the python script add the target
2, found challenge callback to solver.js
3, get challenge
4, close the session
5, return cookies on python script

**Comment by Xoosz** [comment]
Dos = ur real ip

**Comment by Xoosz** [comment]
Method without proxy = ur IP

**Comment by andress134** [comment]
> Method without proxy = ur IP

The script is proxyless = use your server IP
The proxy function look not working im hiting my own server and i see just my server IP
also tested on iplogger and it get just my server ip, no proxies (on all methods not just on the method proxyless)

**Comment by Xoosz** [comment]
> > Method without proxy = ur IP
> 
> The script is proxyless = use your server IP The proxy function look not working im hiting my own server and i see just my server IP also tested on iplogger and it get just my server ip, no proxies (on all methods not just on the method proxyless)

what method u you?

**Comment by andress134** [comment]
> > > Method without proxy = ur IP
> > 
> > 
> > The script is proxyless = use your server IP The proxy function look not working im hiting my own server and i see just my server IP also tested on iplogger and it get just my server ip, no proxies (on all methods not just on the method proxyless)
> 
> what method u use?

pxcfb, cfb, cfpro

**Comment by Atager228** [comment]
> > > > Method without proxy = ur IP
> > > 
> > > 
> > > The script is proxyless = use your server IP The proxy function look not working im hiting my own server and i see just my server IP also tested on iplogger and it get just my server ip, no proxies (on all methods not just on the method proxyless)
> > 
> > 
> > what method u use?
> 
> pxcfb, cfb, cfpro

you added a proxy to the file proxy.txt ?

**Comment by Atager228** [comment]
![image](https://user-images.githubusercontent.com/51260023/161430457-c52ff79c-c040-419a-b624-8ef93f9c274a.png)
Proxies are working, here is my result with IPLogger

**Comment by andress134** [comment]
> ![image](https://user-images.githubusercontent.com/51260023/161430457-c52ff79c-c040-419a-b624-8ef93f9c274a.png) Proxies are working, here is my result with IPLogger

Yes i added, wich any method u tested?

**Comment by HyukIsBack** [comment]
use proxy method
proxy works well
