### ISSUE TITLE
[BUG] Requests just work first time.

### ISSUE THREAD

**Issue by andress134** [HyukIsBack/KARMA-DDoS#16]
Hello i see the script just send requests first time for 60-120 seconds and it stop to send request on the target
I think a sugestion is to make a function to detect when target is down or not or idk
@HyukIsBack

**Comment by HyukIsBack** [comment]
what method u use??

**Comment by andress134** [comment]
> what method u use??



> what method u use??

cfsoc

**Comment by HyukIsBack** [comment]
> > what method u use??
> 
> cfsoc

will be fixed soon
