### ISSUE TITLE
[BUG] Script look patched

### ISSUE THREAD

**Issue by andress134** [HyukIsBack/KARMA-DDoS#18]
hey sir @HyukIsBack  the script look patched
im try to bypass normal uam or no sec  cf normal and can't
bypass function look no working

**Comment by HyukIsBack** [comment]
What method u used

**Comment by andress134** [comment]
> What method u used

cfb cfpro and pxcfb

**Comment by andress134** [comment]
> > > What method u used
> > 
> > 
> > cfb cfpro and pxcfb
> 
> send result

here are no error just script is in still waiting and nothing passing
dont send requests and can't get cookies

**Comment by HyukIsBack** [comment]
> > > > What method u used
> > > 
> > > 
> > > cfb cfpro and pxcfb
> > 
> > 
> > send result
> 
> here are no error just script is in still waiting and nothing passing dont send requests and can't get cookies

cfpro can't bypass cf nosec

**Comment by andress134** [comment]
> > > > > What method u used
> > > > 
> > > > 
> > > > cfb cfpro and pxcfb
> > > 
> > > 
> > > send result
> > 
> > 
> > here are no error just script is in still waiting and nothing passing dont send requests and can't get cookies
> 
> cfpro can't bypass cf nosec

Yes but the others methods also can bypass iuam i think the script got patched
because it is a public script and cloudflare can patched it easy
