### ISSUE TITLE
New methods/features

### ISSUE THREAD

**Issue by SkyWtkhIsBack** [HyukIsBack/KARMA-DDoS#21]
Add support for HTTP/1.3 and HTTP/2
Add the NULL Method (Null UserAgent and ...)
Add HTTPS-SPOOF (My method that can bypass CF, DDoS Guard, Etc)
Add Split Args (Example: cfpro https://example.com 1000 30)
Add methods for Layer 4 (TCP, UDP, ACK, RST, XMAS, DVR, ARD, Etc)

Note: I do not force you to add everything I asked you since that is the owner's decision (You could also add features little by little)

**Comment by HyukIsBack** [comment]
I invite u collaborator.
If u not want, declined it.
I'll add method next update

**Comment by SkyWtkhIsBack** [comment]
![Floppa_Captcha](https://user-images.githubusercontent.com/103963345/166127383-6049e588-48dd-4153-8a52-9de495063d91.jpg)

**Comment by SkyWtkhIsBack** [comment]
![Floppa](https://user-images.githubusercontent.com/103963345/166127404-945b01e4-0680-446c-badd-04a1d1d7da2b.png)
