### ISSUE TITLE
Failed to bypass cf

### ISSUE THREAD

**Issue by nirvash21** [HyukIsBack/KARMA-DDoS#22]
Hi,

Was trying on your script using cf-pro and cf-socket. But it returned Failed to bypass cf. 

Does this script use proxies when attacking? If not, then it might be caused by my server's ip is being blocked by CloudFlare so I need to change my ip.

**Comment by andress134** [comment]
> Hi,
> 
> Was trying on your script using cf-pro and cf-socket. But it returned Failed to bypass cf.
> 
> Does this script use proxies when attacking? If not, then it might be caused by my server's ip is being blocked by CloudFlare so I need to change my ip.

the bypass is patched
this script is dead maybe just if u buy a private version from @HyukIsBack

**Comment by HyukIsBack** [comment]
Bypass not patched
Update chrome(Windows) or re-install it(Linux)
Chrome version 100 -> 101 today

**Comment by nirvash21** [comment]
I have just updated the Chrome but still failed to bypass cf

**Comment by HyukIsBack** [comment]
Test in dstat.cc
It works :)
cfsoc and cfreq only bypass UAM/CAPTCHA
