### ISSUE TITLE
UDP Method

### ISSUE THREAD

**Issue by Vazza202** [HyukIsBack/KARMA-DDoS#26]
Error: Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
TypeError: runsender() missing 1 required positional argument: 'payload'

Everything installed fine too, not sure what's the issue. thanks. I got a private server, my net outputs 10gigs with this 1 server. this threading issue on the UDP only outputs 600mbps

BTW I love this script lol layer 7 works perfectly just layer 4 has issues.

**Comment by HyukIsBack** [comment]
thx
I'll fix it in the next update
