### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by SkyWtkh** [HyukIsBack/KARMA-DDoS#7]
https://github.com/D4RK-4RMY/DarkNet Look at this repository it is the same as yours

**Comment by babodai** [comment]
hello SkyWth you here what a nice attack job my idol yous <3

**Comment by babodai** [comment]
for me can you upload the old files namely ./FORTNITE BYPASS OR OVH-game script

**Comment by HyukIsBack** [comment]
thx skywtkh I checked

**Comment by babodai** [comment]
@HyukIsBack bro pls check discord <3
